/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AppSportsRouteImport } from './routes/_app.sports'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNewRouteImport } from './routes/_app.new'
import { Route as AppFriendsRouteImport } from './routes/_app.friends'
import { Route as AppDiscoverRouteImport } from './routes/_app.discover'
import { Route as AppGamesIdRouteImport } from './routes/_app.games.$id'
import { Route as AppGamesIdEditRouteImport } from './routes/_app.games_.$id.edit'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AppSportsRoute = AppSportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesIdRoute = AppGamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppGamesIdEditRoute = AppGamesIdEditRouteImport.update({
  id: '/games_/$id/edit',
  path: '/games/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/discover': typeof AppDiscoverRoute
  '/friends': typeof AppFriendsRoute
  '/new': typeof AppNewRoute
  '/profile': typeof AppProfileRoute
  '/sports': typeof AppSportsRoute
  '/auth/reset': typeof AuthResetRoute
  '/games/$id': typeof AppGamesIdRoute
  '/games/$id/edit': typeof AppGamesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/discover': typeof AppDiscoverRoute
  '/friends': typeof AppFriendsRoute
  '/new': typeof AppNewRoute
  '/profile': typeof AppProfileRoute
  '/sports': typeof AppSportsRoute
  '/auth/reset': typeof AuthResetRoute
  '/games/$id': typeof AppGamesIdRoute
  '/games/$id/edit': typeof AppGamesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/friends': typeof AppFriendsRoute
  '/_app/new': typeof AppNewRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/sports': typeof AppSportsRoute
  '/auth/reset': typeof AuthResetRoute
  '/_app/games/$id': typeof AppGamesIdRoute
  '/_app/games_/$id/edit': typeof AppGamesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/discover'
    | '/friends'
    | '/new'
    | '/profile'
    | '/sports'
    | '/auth/reset'
    | '/games/$id'
    | '/games/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/discover'
    | '/friends'
    | '/new'
    | '/profile'
    | '/sports'
    | '/auth/reset'
    | '/games/$id'
    | '/games/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/privacy'
    | '/_app/discover'
    | '/_app/friends'
    | '/_app/new'
    | '/_app/profile'
    | '/_app/sports'
    | '/auth/reset'
    | '/_app/games/$id'
    | '/_app/games_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/sports': {
      id: '/_app/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof AppSportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new': {
      id: '/_app/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/friends': {
      id: '/_app/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games/$id': {
      id: '/_app/games/$id'
      path: '/games/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof AppGamesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/games_/$id/edit': {
      id: '/_app/games_/$id/edit'
      path: '/games/$id/edit'
      fullPath: '/games/$id/edit'
      preLoaderRoute: typeof AppGamesIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppNewRoute: typeof AppNewRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSportsRoute: typeof AppSportsRoute
  AppGamesIdRoute: typeof AppGamesIdRoute
  AppGamesIdEditRoute: typeof AppGamesIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDiscoverRoute: AppDiscoverRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppNewRoute: AppNewRoute,
  AppProfileRoute: AppProfileRoute,
  AppSportsRoute: AppSportsRoute,
  AppGamesIdRoute: AppGamesIdRoute,
  AppGamesIdEditRoute: AppGamesIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthResetRoute: typeof AuthResetRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetRoute: AuthResetRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
