/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AppVenuePanelRouteImport } from './routes/_app.venue-panel'
import { Route as AppSportsRouteImport } from './routes/_app.sports'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppOnboardingRouteImport } from './routes/_app.onboarding'
import { Route as AppNewRouteImport } from './routes/_app.new'
import { Route as AppFriendsRouteImport } from './routes/_app.friends'
import { Route as AppDiscoverRouteImport } from './routes/_app.discover'
import { Route as AppAgendaRouteImport } from './routes/_app.agenda'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AppSportsSlugRouteImport } from './routes/_app.sports.$slug'
import { Route as AppProfileIdRouteImport } from './routes/_app.profile.$id'
import { Route as AppGamesIdRouteImport } from './routes/_app.games.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AppGamesIdEditRouteImport } from './routes/_app.games_.$id.edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AppVenuePanelRoute = AppVenuePanelRouteImport.update({
  id: '/venue-panel',
  path: '/venue-panel',
  getParentRoute: () => AppRoute,
} as any)
const AppSportsRoute = AppSportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppFriendsRoute = AppFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSportsSlugRoute = AppSportsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppSportsRoute,
} as any)
const AppProfileIdRoute = AppProfileIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppProfileRoute,
} as any)
const AppGamesIdRoute = AppGamesIdRouteImport.update({
  id: '/games/$id',
  path: '/games/$id',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGamesIdEditRoute = AppGamesIdEditRouteImport.update({
  id: '/games_/$id/edit',
  path: '/games/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/agenda': typeof AppAgendaRoute
  '/discover': typeof AppDiscoverRoute
  '/friends': typeof AppFriendsRoute
  '/new': typeof AppNewRoute
  '/onboarding': typeof AppOnboardingRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/sports': typeof AppSportsRouteWithChildren
  '/venue-panel': typeof AppVenuePanelRoute
  '/auth/reset': typeof AuthResetRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/games/$id': typeof AppGamesIdRoute
  '/profile/$id': typeof AppProfileIdRoute
  '/sports/$slug': typeof AppSportsSlugRoute
  '/games/$id/edit': typeof AppGamesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/agenda': typeof AppAgendaRoute
  '/discover': typeof AppDiscoverRoute
  '/friends': typeof AppFriendsRoute
  '/new': typeof AppNewRoute
  '/onboarding': typeof AppOnboardingRoute
  '/profile': typeof AppProfileRouteWithChildren
  '/sports': typeof AppSportsRouteWithChildren
  '/venue-panel': typeof AppVenuePanelRoute
  '/auth/reset': typeof AuthResetRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/games/$id': typeof AppGamesIdRoute
  '/profile/$id': typeof AppProfileIdRoute
  '/sports/$slug': typeof AppSportsSlugRoute
  '/games/$id/edit': typeof AppGamesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/agenda': typeof AppAgendaRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/friends': typeof AppFriendsRoute
  '/_app/new': typeof AppNewRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/profile': typeof AppProfileRouteWithChildren
  '/_app/sports': typeof AppSportsRouteWithChildren
  '/_app/venue-panel': typeof AppVenuePanelRoute
  '/auth/reset': typeof AuthResetRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_app/games/$id': typeof AppGamesIdRoute
  '/_app/profile/$id': typeof AppProfileIdRoute
  '/_app/sports/$slug': typeof AppSportsSlugRoute
  '/_app/games_/$id/edit': typeof AppGamesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/agenda'
    | '/discover'
    | '/friends'
    | '/new'
    | '/onboarding'
    | '/profile'
    | '/sports'
    | '/venue-panel'
    | '/auth/reset'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/games/$id'
    | '/profile/$id'
    | '/sports/$slug'
    | '/games/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/agenda'
    | '/discover'
    | '/friends'
    | '/new'
    | '/onboarding'
    | '/profile'
    | '/sports'
    | '/venue-panel'
    | '/auth/reset'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/games/$id'
    | '/profile/$id'
    | '/sports/$slug'
    | '/games/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/mcp'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_app/agenda'
    | '/_app/discover'
    | '/_app/friends'
    | '/_app/new'
    | '/_app/onboarding'
    | '/_app/profile'
    | '/_app/sports'
    | '/_app/venue-panel'
    | '/auth/reset'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_app/games/$id'
    | '/_app/profile/$id'
    | '/_app/sports/$slug'
    | '/_app/games_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/venue-panel': {
      id: '/_app/venue-panel'
      path: '/venue-panel'
      fullPath: '/venue-panel'
      preLoaderRoute: typeof AppVenuePanelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sports': {
      id: '/_app/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof AppSportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new': {
      id: '/_app/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/friends': {
      id: '/_app/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AppFriendsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda': {
      id: '/_app/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sports/$slug': {
      id: '/_app/sports/$slug'
      path: '/$slug'
      fullPath: '/sports/$slug'
      preLoaderRoute: typeof AppSportsSlugRouteImport
      parentRoute: typeof AppSportsRoute
    }
    '/_app/profile/$id': {
      id: '/_app/profile/$id'
      path: '/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof AppProfileIdRouteImport
      parentRoute: typeof AppProfileRoute
    }
    '/_app/games/$id': {
      id: '/_app/games/$id'
      path: '/games/$id'
      fullPath: '/games/$id'
      preLoaderRoute: typeof AppGamesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/games_/$id/edit': {
      id: '/_app/games_/$id/edit'
      path: '/games/$id/edit'
      fullPath: '/games/$id/edit'
      preLoaderRoute: typeof AppGamesIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppProfileRouteChildren {
  AppProfileIdRoute: typeof AppProfileIdRoute
}

const AppProfileRouteChildren: AppProfileRouteChildren = {
  AppProfileIdRoute: AppProfileIdRoute,
}

const AppProfileRouteWithChildren = AppProfileRoute._addFileChildren(
  AppProfileRouteChildren,
)

interface AppSportsRouteChildren {
  AppSportsSlugRoute: typeof AppSportsSlugRoute
}

const AppSportsRouteChildren: AppSportsRouteChildren = {
  AppSportsSlugRoute: AppSportsSlugRoute,
}

const AppSportsRouteWithChildren = AppSportsRoute._addFileChildren(
  AppSportsRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppFriendsRoute: typeof AppFriendsRoute
  AppNewRoute: typeof AppNewRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppProfileRoute: typeof AppProfileRouteWithChildren
  AppSportsRoute: typeof AppSportsRouteWithChildren
  AppVenuePanelRoute: typeof AppVenuePanelRoute
  AppGamesIdRoute: typeof AppGamesIdRoute
  AppGamesIdEditRoute: typeof AppGamesIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppFriendsRoute: AppFriendsRoute,
  AppNewRoute: AppNewRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppProfileRoute: AppProfileRouteWithChildren,
  AppSportsRoute: AppSportsRouteWithChildren,
  AppVenuePanelRoute: AppVenuePanelRoute,
  AppGamesIdRoute: AppGamesIdRoute,
  AppGamesIdEditRoute: AppGamesIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthResetRoute: typeof AuthResetRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetRoute: AuthResetRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
